[interface]
Address = 10.100.0.4/24
PrivateKey = WNW6gBQZVtFkFdoWkGUWklts1/3wvHtDzUQpaUxvb2o=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
DNS = 8.8.8.8
ListenPort = 51820

[Peer]
PublicKey = vul6wXx0RaykQvPDgwGBmykntvCt+kk6TCiY6GWEZig=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 202.61.237.213:51820
